language: rust
rust: nightly

env:
  matrix:
    - BACKTRACE=no JEMALLOC=dynamic
    - BACKTRACE=no JEMALLOC=no
    - BACKTRACE=no JEMALLOC=static
    - BACKTRACE=yes JEMALLOC=dynamic
    - BACKTRACE=yes JEMALLOC=no
    - BACKTRACE=yes JEMALLOC=static

install:
  - source .travis.install.sh

script:
  - ./.travis.script.sh

branches:
  only: master

notifications:
  email:
    on_success: never
